name: Flutter AAB Build

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch: # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' #Change this to your Flutter version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

